### ISSUE TITLE
Update Project For Xcode 9 & Swift 4

### ISSUE THREAD

**Issue by leedsalex** [edopelawi/CascadingTableDelegate#14]
Could you please update the project for Xcode 9 & Swift 4. I don't believe there are any changes necessary other than project settings.

**Comment by edopelawi** [comment]
Thanks for the request, @leedsalex ! Sure thing, but let me double-check the UITableView APIs to make sure ;) I'll finish this before 24 hours!

**Comment by edopelawi** [comment]
Fixed on #15. I'll create the new version now.

Cheers,
