### ISSUE TITLE
Build Fails with Carthage Version 0.26.2

### ISSUE THREAD

**Issue by leedsalex** [edopelawi/CascadingTableDelegate#16]
I'm not sure why it fails, but it works with version 0.25.0

**Comment by edopelawi** [comment]
Hey @leedsalex! Thanks for reporting, I'll look at the issue this weekend. May I know the Xcode version you're using?

**Comment by leedsalex** [comment]
Hi @edopelawi Thanks for checking it out for me. I am using Xcode Version 9.1 (9B55)

**Comment by leedsalex** [comment]
Hi @edopelawi Did you get a change to investigate this issue?

**Comment by leedsalex** [comment]
@edopelawi Sorry to nag, any update on this issue or ideas as to why archiving might be failing?

**Comment by leedsalex** [comment]
Hi @edopelawi I was able to figure out what is causing the failure. Please take a look at this ticket: https://github.com/Carthage/Carthage/issues/2275

If you change the `Build Location` from `Legacy` to `Xcode Default` in the CascadingTableDelegate project settings, the Carthage will successfully build the project.

I can make a PR with these changes, just let me know if you need me to.

**Comment by leedsalex** [comment]
@edopelawi I submitted a pull request for your review #17

**Comment by edopelawi** [comment]
Fixed on pull request #17.
