### ISSUE TITLE
Is this really necessary?

### ISSUE THREAD

**Issue by rob-nash** [edopelawi/CascadingTableDelegate#20]
I have re-created most of the demo, without using the assistance of `CascadingTableDelegate` [here](https://github.com/rob-nash/Outdoor). If you check it out you will see that the model isn't big.

I think the problem `CascadingTableDelegate ` sets out to achieve, doesn't exist.

**Comment by edopelawi** [comment]
Hey @rob-nash , thanks for reaching out!

First of all, I should say thank you for analyzing this little library of mine :) and I haven't had the time to review your sample, I guess I'll look at it on the weekends.

Initially, I wanted to create a way to make several section in my table cleanly reusable in for other pages... and I ended up with a full-blown library.

Then again, thank you for reminding me that my work is worthless! It's perfectly what I need right now :)

**Comment by rob-nash** [comment]
Hi @edopelawi no worries it was an interesting idea. I wanted it to work. Did you advertise this somewhere? >800 stars is an achievement.

**Comment by rob-nash** [comment]
I’m sorry if I have made you sad :(
