### ISSUE TITLE
Dynamic cell height doesn't seem to work

### ISSUE THREAD

**Issue by ryanmay** [edopelawi/CascadingTableDelegate#7]
I have been unsuccessful in trying to get dynamic cell height to work with the CascadingTableDelegate.  I can provide a sample project showing the problem if that would help.

**Comment by edopelawi** [comment]
Hi Ryan, sure thing! Kindly share the sample project so I could take a look on it :)

**Comment by ryanmay** [comment]
@edopelawi I sent the sample project to your email

**Comment by edopelawi** [comment]
Ryan, I've checked the issue, and just made [a pull request to fix it.](https://github.com/edopelawi/CascadingTableDelegate/pull/8) Kindly check whether it solves your problem, so I could merge it later! 😄

**Comment by edopelawi** [comment]
Fixed on version 2.0.3! 😄
