### ISSUE TITLE
crash when press "Show me he good stuff" button

### ISSUE THREAD

**Issue by ADevelopStudio** [edopelawi/CascadingTableDelegate#9]
** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'section header height must not be negative - provided height for section 0 is -0.000000'

**Comment by edopelawi** [comment]
Ouch. Thanks for the report, @ADevelopStudio ! May I know the OS version you ran?

**Comment by edopelawi** [comment]
Boy, I just realised `CGFloat.leastNormalMagnitude` won't work anymore :( fixing this right now!

**Comment by edopelawi** [comment]
@ADevelopStudio , I just made [a pull request to fix this](https://github.com/edopelawi/CascadingTableDelegate/pull/10). Kindly check it out if you're available, thanks! :)

**Comment by ADevelopStudio** [comment]
Example still crashes,
however, when I changed all
`CGFloat.leastNormalMagnitude`
to
`CGFloat(1.1)`
is started working well.
**Thanks!**

**Comment by edopelawi** [comment]
Uh-oh. There are some `CGFloat.leastNormalMagnitude` missing in the last pull request? Thanks for checking it out man!

**Comment by edopelawi** [comment]
Checked the repo once again, no `leastNormalMagnitude` left. Closing this issue.
